spring:
  application:
    name: Job-Hunt
  mongodb:
    uri: mongodb://localhost:27017/jobHunt
    auto-index-creation: true

USER_FOUND: User is already registered.
USER_NOT_FOUND: User is not registered.
INVALID_CREDENTIALS: Invalid Credentials.
